### PR TITLE
Update version of Pillow being used.

### PR DESCRIPTION
**Pull request by somexpert**

### CODE REVIEW

**Comment by somexpert** [comment]
ping @ldko, this is ready for review

**Comment by somexpert** [comment]
This also updates uglify-js

**Review by ldko — COMMENTED** [review]
In order to get this to build and run in Docker for me, I had to add `RUN pip install -U pip setuptools` to the Dockerfile before installing the requirements. Otherwise, works for me.

**Comment by somexpert** [comment]
Think we should add that? Couldn't hurt.

**Comment by ldko** [comment]
Yeah, we could add that...not sure why I need it when you don't though...

**Review by ldko — APPROVED** [review]

**Pull request merged**
